-- 将该建表 SQL 语句，添加到 yudao-module-wms-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "wms_tray" (
                                          "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                          "tray_no" int NOT NULL,
                                          "type" varchar NOT NULL,
                                          "max_bind_number" int NOT NULL,
                                          "max_use_number" int NOT NULL,
                                          "status" varchar NOT NULL,
                                          "creator" varchar DEFAULT '',
                                          "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                          "updater" varchar DEFAULT '',
                                          "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                          "deleted" bit NOT NULL DEFAULT FALSE,
                                          "tenant_id" bigint NOT NULL,
                                          PRIMARY KEY ("id")
) COMMENT '托盘表';

-- 将该建表 SQL 语句，添加到 yudao-module-wms-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "wms_storage" (
                                             "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                             "area_id" bigint NOT NULL,
                                             "code" varchar,
                                             "name" varchar,
                                             "status" varchar NOT NULL,
                                             "has_good" varchar NOT NULL,
                                             "has_fire_channel" varchar NOT NULL,
                                             "special_storage" varchar NOT NULL,
                                             "remark" varchar,
                                             "creator" varchar DEFAULT '',
                                             "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             "updater" varchar DEFAULT '',
                                             "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                             "deleted" bit NOT NULL DEFAULT FALSE,
                                             "tenant_id" bigint NOT NULL,
                                             PRIMARY KEY ("id")
) COMMENT '库位表';

CREATE TABLE IF NOT EXISTS "wms_barcode" (
                                             "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                             "barcode" varchar NOT NULL,
                                             "data_source" varchar NOT NULL,
                                             "spec" varchar NOT NULL,
                                             "area" varchar NOT NULL,
                                             "storage" varchar NOT NULL,
                                             "barcode_status" varchar NOT NULL,
                                             "formula_item_id" int,
                                             "ng_site" varchar,
                                             "retest" int,
                                             "formula_id" int,
                                             "tray_id" varchar,
                                             "channel_index" int,
                                             "batch_id" int,
                                             "battery_id" int,
                                             "cab_name" varchar,
                                             "is_locked" bit,
                                             "mes_production_number" varchar NOT NULL,
                                             "customer_number" varchar NOT NULL,
                                             "remark" varchar,
                                             "creator" varchar DEFAULT '',
                                             "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             "updater" varchar DEFAULT '',
                                             "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                             "deleted" bit NOT NULL DEFAULT FALSE,
                                             "tenant_id" bigint NOT NULL,
                                             PRIMARY KEY ("id")
) COMMENT '条码表';

CREATE TABLE IF NOT EXISTS "wms_formula_item" (
                                                  "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                  "serial_number" int,
                                                  "formula_id" varchar,
                                                  "name" varchar,
                                                  "code" varchar,
                                                  "set_time" varchar,
                                                  "status" varchar NOT NULL,
                                                  "rule_id" varchar,
                                                  "creator" varchar DEFAULT '',
                                                  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                  "updater" varchar DEFAULT '',
                                                  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                  "deleted" bit NOT NULL DEFAULT FALSE,
                                                  "tenant_id" bigint NOT NULL,
                                                  "area" varchar,
                                                  "retest_number" int,
                                                  PRIMARY KEY ("id")
) COMMENT '工艺流程子表';

CREATE TABLE IF NOT EXISTS "wms_formula" (
                                             "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                             "code" varchar,
                                             "name" varchar,
                                             "formula_item_list" varchar,
                                             "status" varchar NOT NULL,
                                             "time_out" varchar,
                                             "creator" varchar DEFAULT '',
                                             "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             "updater" varchar DEFAULT '',
                                             "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                             "deleted" bit NOT NULL DEFAULT FALSE,
                                             "tenant_id" bigint NOT NULL,
                                             PRIMARY KEY ("id")
) COMMENT '工艺流程主表';
